# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Khongorzul Tumurbaatar
title: Accountant, Accounting Analysis, Financial Auditor
email: khongorzul.tb@gmail.com
phone: 0097696651441

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: khongorzul-tumurbaatar-83762b252
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Results-driven accounting professional with a strong background in budgeting, forecasting, and management accounting. Expertise in financial reporting, compliance, and process optimization. Adept at strategic planning and problem-solving, with a comprehensive understanding of accounting principles and procedures. Demonstrated success in leveraging accounting software knowledge to provide valuable insights to senior management, driving organizational growth and efficiency. Multilingual and collaborative, committed to achieving excellence in the field of finance.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Level 3 Associate
        sub_title: PWC, Ulaanbaatar
        caption: 2020-12 - Current
        description: |
            - Management of banking processes and transactions
            - Supervision of supplier relations and procurement activities
            - Assistance in monthly cash flow forecasting for enhanced financial planning
            - Coordination of monthly account closures and preparation of quarterly financial reports
            - Evaluation of tender documents to ensure adherence to regulatory requirements
            - Sharing expertise in various accounting software solutions and offering strategic advice to senior management for optimal organizational performance
      - layout: left
        title: Settlement Specialist
        sub_title: Bayanzurkh State fund, Ulaanbaatar
        caption: 2020-03 - 2020-12
        description: |
            - Coordinate and oversee the implementation of budgets for financial institutions, while managing daily expenditure transactions
            - Track account balances and perform regular bank statement reconciliations
            - Evaluate monthly budget performance and identify areas for improvement
            - Accurately record expenditure transactions for financial entities and ensure prompt processing of supporting documentation
      - layout: left
        title: Assistant Accountant
        sub_title: The Coca-Cola Company, Ulaanbaatar
        caption: 2020-03 - 2020-12
        description: |
            - Assist in preparing financial statements and reports
            - Support accounts payable and receivable processes
            - Reconcile bank statements and general ledger accounts
            - Organize and archive source documents for audit purposes
            - Perform data entry and update financial records in accounting software

  - title: Education
    layout: list
    content:
      - layout: left
        title: International Economics
        caption: 2015-09 - 2019-07
        sub_title: Financial University, Moscow
        description: |
          Completed a Bachelor's Degree in Economics, focusing on majors in Accounting, Account Analysis, and Audit. The program provided a comprehensive understanding of economic theories and principles, along with practical knowledge and skills in accounting, financial analysis, and auditing practices. The rigorous curriculum, combined with hands-on learning experiences, prepared me for a successful career in finance and accounting.
      - layout: left
        title: Consolidated Financial Statements
        caption: 2018-09 - 2019-07
        sub_title: KPMG, Moscow
        description: |
          Participated in an intensive, year-long course organized by KPMG, focusing on the preparation and analysis of consolidated financial statements. The course provided in-depth knowledge of accounting standards, principles, and methodologies for the consolidation of financial statements. Through a combination of theoretical instruction and practical exercises, I gained the expertise needed to effectively compile and analyze consolidated financial information, enabling me to contribute meaningfully to any organization's financial management and reporting processes.

  - title: Languages
    layout: text
    content: |
      ðŸ‡ºðŸ‡¸ English: Fluent; experience in international environments.<br>
      ðŸ‡·ðŸ‡º Russian: Fluent; gained from studying in Russia.<br>
      ðŸ‡§ðŸ‡¬ Bulgarian: Fluent; native speaker born in Sofia.<br>
      ðŸ‡²ðŸ‡³ Mongolian: Fluent; native language with local market understanding.<br>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
